name: Lock issues

on:
  schedule:
    # Every day
    - cron: 0 0 * * *

jobs:
  lock-issues:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/lock-threads@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-inactive-days: 90
          process-only: issues
          add-issue-labels: locked
          issue-comment: >
            This issue has been automatically locked since there
            has not been any recent activity after it was closed.
            Please open a new issue for related bugs.
